check50:
  checks:
    hello world:
      - run: python3 hello.py
        stdin:
          - Varsha
          - Nithya
        stdout:
          - Hello, Varsha!
          - Hello, Nithya!
        exit: 0
